# make everything 
all : 
	cd SparseLib++/1.7; make sp;
	cd samtools-0.1.18; make all;
	cd HL; make all;

clean :
	cd HL; make clean; 
	cd samtools-0.1.18; make clean; 
	cd SparseLib++/1.7; make wipe;

 
